console.log('test')

let button0 = Number(document.getElementById("button0").innerHTML)
let button1 = Number(document.getElementById("button1").innerHTML)
let button2 = Number(document.getElementById("button2").innerHTML)
let button3 = Number(document.getElementById("button3").innerHTML)
let button4 = Number(document.getElementById("button4").innerHTML)
let button5 = Number(document.getElementById("button5").innerHTML)
let button6 = Number(document.getElementById("button6").innerHTML)
let button7 = Number(document.getElementById("button7").innerHTML)
let button8 = Number(document.getElementById("button8").innerHTML)
let button9 = Number(document.getElementById("button9").innerHTML)

let button_logo = Number(document.getElementById("logo").innerHTML)
let button_dot = Number(document.getElementById("dot").innerHTML)
let button_divide = Number(document.getElementById("divide").innerHTML)
let button_myltiply = Number(document.getElementById("myltiply").innerHTML)
let button_minus = Number(document.getElementById("minus").innerHTML)
let button_plus = Number(document.getElementById("plus").innerHTML)
let button_equal = Number(document.getElementById("equal").innerHTML)
// button1 = Number(button1.innerHTML)
console.log(typeof button1, button1)